name: zookeeper_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  day_night_time_picker: ^1.3.0
  dropdown_button2: ^2.3.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_secure_storage: ^8.0.0
  http: ^0.13.6
  intl: ^0.18.1
  lottie: ^2.3.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/liongateApp.png"
  min_sdk_android: 20

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo/liongateApp.png
  branding: assets/images/logo/Logo.png
  color_dark: "#000000"
  image_dark: assets/images/logo/liongateApp.png
  branding_dark: assets/images/logo/Logo.png

  android_12:
    image: assets/images/logo/liongateApp.png
    icon_background_color: "#000000"
    image_dark: assets/images/logo/liongateApp.png
    icon_background_color_dark: "#000000"

  web: false

flutter:
  uses-material-design: true
  assets:
    - .env 
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/animal/
    - assets/lotties/ 

  fonts:
    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto-Regular.ttf 
      
    - family: OpenSans
      fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf      
